# Usamos una imagen base de Java con JDK 17 (o la que uses)
FROM eclipse-temurin:17-jdk-alpine

# Directorio de la app en el contenedor
WORKDIR /app

# Copiamos el JAR generado por Spring Boot
COPY target/formula1-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto 8080
EXPOSE 8080

# Comando para ejecutar la app
ENTRYPOINT ["java", "-jar", "abpp.jar"]