spring.application.name=formula1

spring.datasource.url=jdbc:mariadb://bbdd:3306/formula1
spring.datasource.username=formula1user
spring.datasource.password=Eavne,e1m

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl